### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by aslagle** [edrlab/r2-streamer-js#1]
I'm getting this error on a few different epubs:
```
$ yarn run cli /Users/amyslagle/Downloads/677.epub 
yarn run v0.21.3
$ node './dist/src/cli.js' /Users/amyslagle/Downloads/677.epub
process.cwd():
/Users/amyslagle/dev/r2-streamer-js
__dirname:
/Users/amyslagle/dev/r2-streamer-js/dist/src
args:
[ '/Users/amyslagle/Downloads/677.epub' ]
/Users/amyslagle/Downloads/677.epub
== EpubParser: reject
TypeError: Cannot read property 'push' of undefined
    at EpubParser.fillTOCFromNavPoint (/Users/amyslagle/dev/r2-streamer-js/dist/src/parser/epub.js:945:13)
    at ncx.Points.forEach (/Users/amyslagle/dev/r2-streamer-js/dist/src/parser/epub.js:917:22)
    at Array.forEach (native)
    at EpubParser.fillTOCFromNCX (/Users/amyslagle/dev/r2-streamer-js/dist/src/parser/epub.js:916:24)
    at forEach (/Users/amyslagle/dev/r2-streamer-js/dist/src/parser/epub.js:172:34)
    at Array.forEach (native)
    at Promise (/Users/amyslagle/dev/r2-streamer-js/dist/src/parser/epub.js:91:22)
    at EpubParser.createPublicationPromise (/Users/amyslagle/dev/r2-streamer-js/dist/src/parser/epub.js:48:16)
    at Parse.zipPromise.then (/Users/amyslagle/dev/r2-streamer-js/dist/src/parser/epub.js:44:25)
false
✨  Done in 0.48s.
```

**Comment by aslagle** [comment]
Here's an example epub that gives me that error: http://oabooks.nypl.org/ISBN/9781682280997.epub

**Comment by aslagle** [comment]
Looks like it's fixed now :)
