### ISSUE TITLE
gitrev.json Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by danielweck** [edrlab/r2-streamer-js#16]
https://readium2.herokuapp.com/version/show

```
SyntaxError: /app/dist/gitrev.json: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:681:27)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Server.expressApp.get (/app/dist/es8-es2017/src/http/server.js:184:29)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at param (/app/node_modules/express/lib/router/index.js:354:14)
    at param (/app/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/app/node_modules/express/lib/router/index.js:410:3)
```

https://github.com/edrlab/r2-streamer-js-dist/blob/develop/dist/gitrev.json
and
https://rawgit.com/edrlab/r2-streamer-js-dist/develop/dist/gitrev.json

See:
https://github.com/edrlab/r2-streamer-js/blob/develop/package-scripts.cson#L281

**Comment by danielweck** [comment]
Fixed via: https://github.com/edrlab/r2-streamer-js/commit/79ff6c944d62d6996e23b3f75d4790b0920ca5a3

(
https://raw.githubusercontent.com
instead of:
https://rawgit.com
)
