### ISSUE TITLE
Broken deployed app on Now.sh (works in Heroku)

### ISSUE THREAD

**Issue by danielweck** [edrlab/r2-streamer-js#33]
```
(node:80) UnhandledPromiseRejectionWarning: TypeError: obj.hasOwnProperty is not a function
    at Array.forEach (<anonymous>)
    at Object.keys.forEach (/home/nowuser/src/node_modules/r2-utils-js/dist/es8-es2017/src/_utils/JsonUtils.js:32:21)
    at traverseJsonObjects_ (/home/nowuser/src/node_modules/r2-utils-js/dist/es8-es2017/src/_utils/JsonUtils.js:31:26)
    at Object.keys.forEach (/home/nowuser/src/node_modules/r2-utils-js/dist/es8-es2017/src/_utils/JsonUtils.js:35:21)
    at Array.forEach (<anonymous>)
    at traverseJsonObjects_ (/home/nowuser/src/node_modules/r2-utils-js/dist/es8-es2017/src/_utils/JsonUtils.js:31:26)
    at Object.keys.forEach (/home/nowuser/src/node_modules/r2-utils-js/dist/es8-es2017/src/_utils/JsonUtils.js:35:21)
    at Array.forEach (<anonymous>)
    at traverseJsonObjects_ (/home/nowuser/src/node_modules/r2-utils-js/dist/es8-es2017/src/_utils/JsonUtils.js:31:26)
    at Object.keys.forEach (/home/nowuser/src/node_modules/r2-utils-js/dist/es8-es2017/src/_utils/JsonUtils.js:35:21)
    at Array.forEach (<anonymous>)
    at traverseJsonObjects_ (/home/nowuser/src/node_modules/r2-utils-js/dist/es8-es2017/src/_utils/JsonUtils.js:31:26)
    at traverseJsonObjects_ (/home/nowuser/src/node_modules/r2-utils-js/dist/es8-es2017/src/_utils/JsonUtils.js:26:17)
    at Object.keys.forEach (/home/nowuser/src/node_modules/r2-utils-js/dist/es8-es2017/src/_utils/JsonUtils.js:35:21)
    at Array.forEach (<anonymous>)
    at traverseJsonObjects_ (/home/nowuser/src/node_modules/r2-utils-js/dist/es8-es2017/src/_utils/JsonUtils.js:31:26)
(node:80) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by danielweck** [comment]
Test:
https://readium2.now.sh

vs.
https://readium2.herokuapp.com

**Comment by danielweck** [comment]
NodeJS runtime:
Now: `10.7.0`
Heroku: `10.9.0`

**Comment by danielweck** [comment]
NPM:
Heroku: `6.4.0`
Now: `6.1.0`

**Comment by danielweck** [comment]
TypeScript code reference:
https://github.com/readium/r2-utils-js/blob/023fdd0391f5ed15f30fdfc8419ea74c750d5257/src/_utils/JsonUtils.ts#L44

**Comment by danielweck** [comment]
Javascript code reference (ES8-2017):
https://github.com/edrlab/r2-utils-js-dist/blob/bcb231232fa7a6b0dda8bae4ee8b6775b3e82e5c/dist/es8-es2017/src/_utils/JsonUtils.js#L32

**Comment by danielweck** [comment]
This looks like a TAJSON serialization failure. There is another error, probably related:
https://r2-streamer-js-gizgtwvnnp.now.sh/pub/L2hvbWUvbm93dXNlci9zcmMvbWlzYy9lcHVicy93YXN0ZWxhbmQtb3RmLW9iZl9MQ1BfZGFuLmVwdWI%3D/manifest.json
```
Internal Server Error

TypeError: lcpl.init is not a function
```

**Comment by danielweck** [comment]
Tried to manually force NPM install dependencies into node_modules, to no avail.
https://github.com/readium/r2-streamer-js/commit/27f3d69ddbee4da724ba49463ee421aa7dfd3ebe

This bizarre bug looks specific to Now.sh, and I think the problem started since we migrated `r2-xxx-js` packages from GitHub "dist" repositories to proper NPM with semantic versioning (thus why I thought it could be a NPM cache issue in Now.sh infrastructure)

**Comment by danielweck** [comment]
Now.sh documentation:
https://zeit.co/docs/deployment-types/node
https://zeit.co/blog/faster-javascript-deployments

**Comment by danielweck** [comment]
Works fine now (probably a temporary NPM issue)
