### ISSUE TITLE
Need to update Dockerfile to node:20

### ISSUE THREAD

**Issue by panaC** [edrlab/r2-streamer-js#74]
https://github.com/readium/r2-streamer-js/blob/9e75821a12ac775e8ab2dd6e36c3064e6db6c9c8/Dockerfile#L1C8-L1C13

https://github.com/readium/r2-streamer-js/runs/30450764342

**Comment by panaC** [comment]
cf build pipeline: 
```
starting build "54d87f59-1e1e-42e5-ac55-e3de582314af"

FETCHSOURCE
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /workspace/.git/
From https://github.com/readium/r2-streamer-js
 * branch            9e75821a12ac775e8ab2dd6e36c3064e6db6c9c8 -> FETCH_HEAD
HEAD is now at 9e75821 v1.0.48
BUILD
Starting Step #0 - "Build"
Step #0 - "Build": Already have image (with digest): gcr.io/cloud-builders/docker
Step #0 - "Build": Sending build context to Docker daemon  4.091MB

Step #0 - "Build": Step 1/6 : FROM node:16
Step #0 - "Build": 16: Pulling from library/node
Step #0 - "Build": 311da6c465ea: Pulling fs layer
Step #0 - "Build": 7e9bf114588c: Pulling fs layer
Step #0 - "Build": ffd9397e94b7: Pulling fs layer
Step #0 - "Build": 513d77925604: Pulling fs layer
Step #0 - "Build": ae3b95bbaa61: Pulling fs layer
Step #0 - "Build": 0e421f66aff4: Pulling fs layer
Step #0 - "Build": ca266fd61921: Pulling fs layer
Step #0 - "Build": ee7d78be1eb9: Pulling fs layer
Step #0 - "Build": ae3b95bbaa61: Waiting
Step #0 - "Build": 513d77925604: Waiting
Step #0 - "Build": 0e421f66aff4: Waiting
Step #0 - "Build": ca266fd61921: Waiting
Step #0 - "Build": ee7d78be1eb9: Waiting
Step #0 - "Build": 7e9bf114588c: Verifying Checksum
Step #0 - "Build": 7e9bf114588c: Download complete
Step #0 - "Build": 311da6c465ea: Verifying Checksum
Step #0 - "Build": 311da6c465ea: Download complete
Step #0 - "Build": ffd9397e94b7: Verifying Checksum
Step #0 - "Build": ffd9397e94b7: Download complete
Step #0 - "Build": ae3b95bbaa61: Verifying Checksum
Step #0 - "Build": ae3b95bbaa61: Download complete
Step #0 - "Build": ca266fd61921: Verifying Checksum
Step #0 - "Build": ca266fd61921: Download complete
Step #0 - "Build": ee7d78be1eb9: Verifying Checksum
Step #0 - "Build": ee7d78be1eb9: Download complete
Step #0 - "Build": 0e421f66aff4: Verifying Checksum
Step #0 - "Build": 0e421f66aff4: Download complete
Step #0 - "Build": 513d77925604: Verifying Checksum
Step #0 - "Build": 513d77925604: Download complete
Step #0 - "Build": 311da6c465ea: Pull complete
Step #0 - "Build": 7e9bf114588c: Pull complete
Step #0 - "Build": ffd9397e94b7: Pull complete
Step #0 - "Build": 513d77925604: Pull complete
Step #0 - "Build": ae3b95bbaa61: Pull complete
Step #0 - "Build": 0e421f66aff4: Pull complete
Step #0 - "Build": ca266fd61921: Pull complete
Step #0 - "Build": ee7d78be1eb9: Pull complete
Step #0 - "Build": Digest: sha256:f77a1aef2da8d83e45ec990f45df50f1a286c5fe8bbfb8c6e4246c6389705c0b
Step #0 - "Build": Status: Downloaded newer image for node:16
Step #0 - "Build":  ---> 1ddc7e4055fd
Step #0 - "Build": Step 2/6 : WORKDIR /streamer
Step #0 - "Build":  ---> Running in 4c2ffe2ae4a4
Step #0 - "Build": Removing intermediate container 4c2ffe2ae4a4
Step #0 - "Build":  ---> 4a672a19ab95
Step #0 - "Build": Step 3/6 : COPY . ./
Step #0 - "Build":  ---> f612ff1b62e8
Step #0 - "Build": Step 4/6 : RUN npm ci && npm run build
Step #0 - "Build":  ---> Running in 4c28678ebe6c
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: 'r2-streamer-js@1.0.48',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '>=20.0.0', npm: '>=10.0.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: '@typescript-eslint/eslint-plugin@8.6.0',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: '@typescript-eslint/parser@8.6.0',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: '@typescript-eslint/scope-manager@8.6.0',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: '@typescript-eslint/type-utils@8.6.0',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: '@typescript-eslint/types@8.6.0',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: '@typescript-eslint/typescript-estree@8.6.0',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: '@typescript-eslint/utils@8.6.0',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: '@typescript-eslint/visitor-keys@8.6.0',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: 'r2-lcp-js@1.0.41',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '>=20.0.0', npm: '>=10.0.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: 'r2-opds-js@1.0.44',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '>=20.0.0', npm: '>=10.0.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: 'r2-shared-js@1.0.75',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '>=20.0.0', npm: '>=10.0.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: 'r2-utils-js@1.0.39',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '>=20.0.0', npm: '>=10.0.0' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: 'rimraf@6.0.1',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '20 || >=22' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: 'glob@11.0.0',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '20 || >=22' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: 'jackspeak@4.0.1',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '20 || >=22' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: 'lru-cache@11.0.1',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '20 || >=22' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: 'minimatch@10.0.1',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '20 || >=22' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN EBADENGINE Unsupported engine {
Step #0 - "Build": npm WARN EBADENGINE   package: 'path-scurry@2.0.0',
Step #0 - "Build": npm WARN EBADENGINE   required: { node: '20 || >=22' },
Step #0 - "Build": npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Step #0 - "Build": npm WARN EBADENGINE }
Step #0 - "Build": npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
Step #0 - "Build": npm WARN deprecated har-validator@5.1.5: this library is no longer supported
Step #0 - "Build": npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
Step #0 - "Build": npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
Step #0 - "Build": npm WARN deprecated date-format@0.0.2: 0.x is no longer supported. Please upgrade to 4.x or higher.
Step #0 - "Build": npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
Step #0 - "Build": npm WARN deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
Step #0 - "Build": npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
Step #0 - "Build": npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Step #0 - "Build": npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
Step #0 - "Build": npm WARN deprecated highlight.js@9.12.0: Version no longer supported. Upgrade to @latest
Step #0 - "Build": 
Step #0 - "Build": added 796 packages, and audited 797 packages in 16s
Step #0 - "Build": 
Step #0 - "Build": 124 packages are looking for funding
Step #0 - "Build":   run `npm fund` for details
Step #0 - "Build": 
Step #0 - "Build": 17 vulnerabilities (15 moderate, 2 high)
Step #0 - "Build": 
Step #0 - "Build": To address issues that do not require attention, run:
Step #0 - "Build":   npm audit fix
Step #0 - "Build": 
Step #0 - "Build": To address all issues possible (including breaking changes), run:
Step #0 - "Build":   npm audit fix --force
Step #0 - "Build": 
Step #0 - "Build": Some issues need review, and may require choosing
Step #0 - "Build": a different dependency.
Step #0 - "Build": 
Step #0 - "Build": Run `npm audit` for details.
Step #0 - "Build": npm notice 
Step #0 - "Build": npm notice New major version of npm available! 8.19.4 -> 10.8.3
Step #0 - "Build": npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.3>
Step #0 - "Build": npm notice Run `npm install -g npm@10.8.3` to update!
Step #0 - "Build": npm notice 
Step #0 - "Build": 
Step #0 - "Build": > r2-streamer-js@1.0.48 prebuild
Step #0 - "Build": > npm run lint
Step #0 - "Build": 
Step #0 - "Build": 
Step #0 - "Build": > r2-streamer-js@1.0.48 lint
Step #0 - "Build": > npm run lint:all && npm run lint:typescript:full
Step #0 - "Build": 
Step #0 - "Build": 
Step #0 - "Build": > r2-streamer-js@1.0.48 lint:all
Step #0 - "Build": > eclint check "**/*" "!**/*.node" "!.git/**/*" "!node_modules*/**/*" "!dist/**/*" "!misc/**/*" "!misc/json-schema/**/*" "!now/**/*" "!.vscode/**/*" "!.history/**/*" "!**/.DS_Store" "!**/*.epub" "!**/*.cbz" "!**/*.jpg" "!**/*.jpeg" "!**/*.png" "!**/*.log"
Step #0 - "Build": 
Step #0 - "Build": 
Step #0 - "Build": > r2-streamer-js@1.0.48 lint:typescript:full
Step #0 - "Build": > eslint "src/**/*.ts"
Step #0 - "Build": 
Step #0 - "Build": 
Step #0 - "Build": Oops! Something went wrong! :(
Step #0 - "Build": 
Step #0 - "Build": ESLint: 8.57.1
Step #0 - "Build": 
Step #0 - "Build": ReferenceError: Error while loading rule '@typescript-eslint/no-unused-vars': structuredClone is not defined
Step #0 - "Build": Occurred while linting /streamer/src/declarations.d.ts
Step #0 - "Build":     at applyDefault (/streamer/node_modules/@typescript-eslint/utils/dist/eslint-utils/applyDefault.js:14:21)
Step #0 - "Build":     at Object.create (/streamer/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:30:72)
Step #0 - "Build":     at createRuleListeners (/streamer/node_modules/eslint/lib/linter/linter.js:895:21)
Step #0 - "Build":     at /streamer/node_modules/eslint/lib/linter/linter.js:1066:110
Step #0 - "Build":     at Array.forEach (<anonymous>)
Step #0 - "Build":     at runRules (/streamer/node_modules/eslint/lib/linter/linter.js:1003:34)
Step #0 - "Build":     at Linter._verifyWithoutProcessors (/streamer/node_modules/eslint/lib/linter/linter.js:1355:31)
Step #0 - "Build":     at Linter._verifyWithConfigArray (/streamer/node_modules/eslint/lib/linter/linter.js:1807:21)
Step #0 - "Build":     at Linter.verify (/streamer/node_modules/eslint/lib/linter/linter.js:1437:65)
Step #0 - "Build":     at Linter.verifyAndFix (/streamer/node_modules/eslint/lib/linter/linter.js:2068:29)
Step #0 - "Build": The command '/bin/sh -c npm ci && npm run build' returned a non-zero code: 2
Finished Step #0 - "Build"
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 2
Step #0 - "Build": 

````
